language: cpp
compiler: g++

sudo: required

before_install:
- sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
- sudo apt-get update -qq

install:
- sudo apt-get install -qq g++-4.8

script:
 - g++-4.8 -std=c++11 -Wall -Wextra -pedantic source/AStar.cpp main.cpp -o app
 - ./app